Repository Rapteon/air-synth, pull requests merged in 2025-04, with the labels that each got.

#29 Config cleanup
  archived/data-interrupt/GPIOEVENT.h
  archived/data-interrupt/MPU6050.h
  archived/data-interrupt/gpioevent.cpp
  archived/data-interrupt/main.cpp
  archived/data-interrupt/mpu.cpp
  examples/mpu_2sensors.cpp
  src/mpu6050_old.cpp
Labels: config

#32 Updated website.
  index.html
Labels: enhancement

#31 Removed unused MPU6050 config file.
  include/IMU/MPU6050Config.h
Labels: config

#30 Removed commented code and fixed two TODO items.
  include/Button/Button.h
  src/Button/Button.cpp
Labels: bug, enhancement

#35 Updated README with link to hardware section and the about page.
  README.md
Labels: documentation

#37 Feature tone gen
  CMakeLists.txt
  include/ControllerEvent/ControllerEvent.h
  include/IMU/IMU.h
  include/IMU/MPU6050.h
  include/Synth/Synth.h
  include/SynthConfig.h
  mpu6050.cpp
  mpu6050.h
  src/Button/Button.cpp
  src/ControllerEvent/ControllerEvent.cpp
  src/IMU/MPU6050.cpp
  src/Synth/Synth.cpp
  src/main.cpp
Labels: enhancement

#39 Removed unused files.
  mpu6050.cpp
  mpu6050.h
Labels: config

#40 Update README.md
  README.md
Labels: documentation
