Repository Rapteon/air-synth, pull requests merged in 2025-03, with the labels that each got.

#10 Basic CMake project structure added
  .gitignore
  CMakeLists.txt
  README.md
  src/CMakeLists.txt
  src/mpu6050.cpp
  tests/CMakeLists.txt
Labels: config

#12 Feature imu two sensors
  src/mpu_2sensors.cpp
Labels: enhancement

#14 Updated README.md with link to Wiki page.
  README.md
Labels: documentation

#16 Moved website files to `website` folder.
  website/images/air-synth-header.jpg
  website/images/hardware-diagram.png
  website/images/software-diagram.png
  website/index.html
  website/styles.css
Labels: config

#17 Change folder name from `website` to `docs`
  docs/images/air-synth-header.jpg
  docs/images/hardware-diagram.png
  docs/images/software-diagram.png
  docs/index.html
  docs/styles.css
Labels: config

#19 Removed website related files from main branch.
  docs/images/air-synth-header.jpg
  docs/images/hardware-diagram.png
  docs/images/software-diagram.png
  docs/index.html
  docs/styles.css
  website/images/air-synth-header.jpg
  website/images/hardware-diagram.png
  website/images/software-diagram.png
  website/index.html
  website/styles.css
Labels: config

#20 Rewrote code structure to handle interrupts from Button
  .gitignore
  CMakeLists.txt
  include/Button/Button.h
  include/IMU/IMU.h
  include/IMU/MPU6050.h
  include/IMU/MPU6050Config.h
  include/SynthConfig.h
  src/Button/Button.cpp
  src/IMU/MPU6050.cpp
  src/main.cpp
  src/mpu6050_old.cpp
  src/mpu_2sensors.cpp
Labels: enhancement

#23 64ref imu interrupt test program
  Codes for IMU/interrupt/generating interrupts/first-debugging.cpp
  Codes for IMU/interrupt/generating interrupts/first.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/GPIOevent.h
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050.h
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050_interface-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050_interface.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/RM-MPU-60xxA_rev_4-736751.pdf
  Codes for IMU/interrupt/organised-interrupt-pushbutton/gpioevent-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/gpioevent.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/interrupthandler.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main-new.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/newmpuinterface.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/raspberry-pi-4-reduced-schematics.pdf
  Codes for IMU/threads-mahony/MahonyAHRS.cpp
  Codes for IMU/threads-mahony/MahonyAHRS.h
  Codes for IMU/threads-mahony/multithreadframework.cpp
  Meghdad/mpu-threads.cpp
  Meghdad/thread1-FIFO.cpp
  Mohammed/README.md
  examples/GPIOEVENT.h
  examples/MPU6050.h
  examples/gpioevent.cpp
  examples/main.cpp
  examples/mpu.cpp
  pb-int/GPIOEVENT.h
  pb-int/MPU6050.h
  pb-int/gpioevent.cpp
  pb-int/main.cpp
  pb-int/mpu.cpp
Labels: enhancement

#24 removed unnecessary files
  Codes for IMU/interrupt/generating interrupts/first-debugging.cpp
  Codes for IMU/interrupt/generating interrupts/first.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/GPIOevent.h
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050.h
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050_interface-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/MPU6050_interface.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/RM-MPU-60xxA_rev_4-736751.pdf
  Codes for IMU/interrupt/organised-interrupt-pushbutton/gpioevent-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/gpioevent.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/interrupthandler.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main-1.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main-new.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/main.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/newmpuinterface.cpp
  Codes for IMU/interrupt/organised-interrupt-pushbutton/raspberry-pi-4-reduced-schematics.pdf
  Codes for IMU/threads-mahony/MahonyAHRS.cpp
  Codes for IMU/threads-mahony/MahonyAHRS.h
  Codes for IMU/threads-mahony/multithreadframework.cpp
  Meghdad/mpu-threads.cpp
  Meghdad/thread1-FIFO.cpp
  Mohammed/README.md
  pb-int/GPIOEVENT.h
  pb-int/MPU6050.h
  pb-int/gpioevent.cpp
  pb-int/main.cpp
  pb-int/mpu.cpp
Labels: config
